### EMA Data ###

INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Wasteland", "27.94");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Sylvan Library", "15.73");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Sensei's Divining Top", "14.24");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Entomb", "12.07");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Enlightened Tutor", "11.68");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Maze of Ith", "9.49");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Toxic Deluge", "8");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Mystical Tutor", "6.41");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Wrath of God", "6.14");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Gamble", "6");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Vindicate", "5.69");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Green Sun's Zenith", "5.69");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Sinkhole", "4.67");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Deathrite Shaman", "4.54");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Heritage Druid", "4.42");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Winter Orb", "3.61");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Shardless Agent", "3.6");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Duplicant", "3.47");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Isochron Scepter", "3.37");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Baleful Strix", "2.99");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Mother of Runes", "2.34");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Karmic Guide", "2.24");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Regal Force", "2.02");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Siege-Gang Commander", "1.67");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Imperious Perfect", "1.55");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Eight-and-a-Half-Tails", "1.41");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Arcanis the Omnipotent", "1.3");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Nevinyrral's Disk", "1.24");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Goblin Charbelcher", "1.19");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Brago King Eternal", "1.17");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Ichorid", "1.16");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Visara the Dreadful", "1");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Malicious Affliction", "0");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Unexpectedly Absent", "0");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Dualcaster Mage", "0");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Xantid Swarm", "0");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Sulfuric Vortex", "0");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Control Magic", "0");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Inkwell Leviathan", "0");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Braids Cabal Minion", "0");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Future Sight", "0");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Silvos Rogue Elemental", "0");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Glare of Subdual", "0");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Jareth Leonine Titan", "0");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Serendib Efreet", "0");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Diminishing Returns", "0");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Void", "0");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Pyrokinesis", "0");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Rorix Bladewing", "0");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Goblin Trenches", "0");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Call the Skybreaker", "0");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Giant Solifuge", "0");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "EMA", "premium", "Crater Hellion", "0");
INSERT INTO mythic_table (rarity, set_name, type, name, price) VALUES("Mythic", "EMA", "premium", "Force of Will", "79.99");
INSERT INTO mythic_table (rarity, set_name, type, name, price) VALUES("Mythic", "EMA", "premium", "Mana Crypt", "77.59");
INSERT INTO mythic_table (rarity, set_name, type, name, price) VALUES("Mythic", "EMA", "premium", "Jace, the Mind Sculptor", "63.64");
INSERT INTO mythic_table (rarity, set_name, type, name, price) VALUES("Mythic", "EMA", "premium", "Vampiric Tutor", "42");
INSERT INTO mythic_table (rarity, set_name, type, name, price) VALUES("Mythic", "EMA", "premium", "Karakas", "38.45");
INSERT INTO mythic_table (rarity, set_name, type, name, price) VALUES("Mythic", "EMA", "premium", "Sneak Attack", "20.76");
INSERT INTO mythic_table (rarity, set_name, type, name, price) VALUES("Mythic", "EMA", "premium", "Chrome Mox", "15.9");
INSERT INTO mythic_table (rarity, set_name, type, name, price) VALUES("Mythic", "EMA", "premium", "Natural Order", "14.9");
INSERT INTO mythic_table (rarity, set_name, type, name, price) VALUES("Mythic", "EMA", "premium", "Dack Fayden", "13.77");
INSERT INTO mythic_table (rarity, set_name, type, name, price) VALUES("Mythic", "EMA", "premium", "Maelstrom Wanderer", "8.41");
INSERT INTO mythic_table (rarity, set_name, type, name, price) VALUES("Mythic", "EMA", "premium", "Necropotence", "7.7");
INSERT INTO mythic_table (rarity, set_name, type, name, price) VALUES("Mythic", "EMA", "premium", "Argothian Enchantress", "5.14");
INSERT INTO mythic_table (rarity, set_name, type, name, price) VALUES("Mythic", "EMA", "premium", "Balance", "1.79");
INSERT INTO mythic_table (rarity, set_name, type, name, price) VALUES("Mythic", "EMA", "premium", "Worldgorger Dragon", "1.25");
INSERT INTO mythic_table (rarity, set_name, type, name, price) VALUES("Mythic", "EMA", "premium", "Sphinx of the Steel Wind", "1.1");


### MM17 Data ###

INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "MM17", "premium", "Scalding Tarn", "56.99");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "MM17", "premium", "Verdant Catacombs", "44.96");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "MM17", "premium", "Misty Rainforest", "32.24");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "MM17", "premium", "Arid Mesa", "30");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "MM17", "premium", "Marsh Flats", "29.99");
INSERT INTO rare_table (rarity, set_name, type, name, price) VALUES("Rare", "MM17", "premium", "Blood Moon", "19.51");
INSERT INTO rare_table (rarity, set_name, type, ...